
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Cảnh báo !!!</h3>
            </div>
            <div class="panel-body">
                <div class="alert alert-danger">
                    Bạn đang truy cập vào khu vực trái phép
                    <br>
                    +Nếu bạn chưa đăng nhập thì hãy đăng nhập rồi truy cập lại <br>
                    +Nếu đã đăng nhập mà vẫn hiện thông báo nghĩa là tài khoản của bạn chưa được cấp quyền để truy cập trang này!

                </div>
            </div>
        </div>
    </div>
</div>
