<?php
/**
 * Created by PhpStorm.
 * User: Thai Duc
 * Date: 14-Mar-18
 * Time: 2:09 AM
 */
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nhập email</h3>
            </div>
            <div class="panel-body">
                <?php
                if (!empty($error)) {
                    echo "<div class='alert-danger alert'> ";
                        echo $error;
                    echo "</div>";
                }
                ?>
                <?php
                if (!empty($message)) {
                    echo "<div class='alert-success alert'> ";
                    if(is_array($message)){
                        echo $message[0];
                    }else{
                        echo $message;
                    }
                    echo "</div>";
                }
                ?>

                <?php
                $form->prepare();
                $form->setAttribute('action',$this->url('admin/verify',array('action'=>'forgot')));

                echo $this->form()->openTag($form);
                echo "<div class='form-group'>";
                echo $this->formElement($form->get('email'));
                echo $this->formElementErrors($form->get('email'));
                echo "</div>";

                echo $this->captcha->getHTML();

                echo $this->formElement($form->get('submit'));
                echo $this->form()->closeTag();

                ?>

            </div>
        </div>
    </div>
</div>
