<?php
/**
 * Created by PhpStorm.
 * User: Thai Duc
 * Date: 14-Mar-18
 * Time: 2:09 AM
 */
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Please Sign In</h3>
            </div>
            <div class="panel-body">
                <?php
                if (!empty($error)) {
                    echo "<div class='alert-danger alert'> ";
                        echo $error;
                    echo "</div>";
                }
                ?>
                <?php
                if (!empty($flash)) {
                    echo "<div class='alert-success alert'> ";
                    echo $flash[0];
                    echo "</div>";
                }
                ?>

                <?php
                $form->prepare();
                $form->setAttribute('action',$this->url('admin/verify',array('action'=>'login')));

                echo $this->form()->openTag($form);

                echo "<div class='form-group'>";
                echo $this->formElement($form->get('email'));
                echo $this->formElementErrors($form->get('email'));
                echo "</div>";

                echo "<div class='form-group'>";
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'));
                echo "</div>";

                echo "<div class='checkbox'>";
                echo $this->formElement($form->get('remember'))." ";
                echo $this->formLabel($form->get('remember'));
                echo "</div>";

                echo $this->formElement($form->get('submit'));

                echo $this->form()->closeTag();

                ?>
            </div>
        </div>
    </div>
</div>
