<?php
echo $this->headScript()
    ->appendFile($this->basePath().'/js/ckeditor/ckeditor.js')
    ->appendFile($this->basePath().'/js/ckeditor/adapters/jquery.js');

?>
<script>

    var BASEPATH = "<?php echo $this->basePath().'/js/ckeditor'; ?>";

    $(document).ready(function () {
        CKEDITOR.replace( 'descriptionEditor', {

            filebrowserBrowseUrl : BASEPATH +'/ckfinder/ckfinder.html',
            filebrowserImageBrowseUrl: BASEPATH +'/ckfinder/ckfinder.html?type=Images',
            filebrowserFlashBrowseUrl : BASEPATH +'/ckfinder/ckfinder.html?type=Flash',
            filebrowserUploadUrl : BASEPATH +'/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserImageUploadUrl : BASEPATH +'/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
            filebrowserFlashUploadUrl : BASEPATH +'/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
        });

//        var editor = CKEDITOR.replace( 'descriptionEditor' );
//        CKFinder.setupCKEditor( editor );
//        var editor = CKEDITOR.replace( 'descriptionEditor' );
//        CKFinder.setupCKEditor( editor, null, { type: 'Files', currentFolder: '/public/data/' } );
    })
</script>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Thể loại</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Thêm thể loại mới
            </div>
            <div class="panel-body">
                <div class="row">
                    <?php
                    $form = $this->form;
                    $form->prepare();
                    $form->setAttribute('action', $this->url('admin/category', array('action' => 'add')));

                    echo $this->form()->openTag($form);
                    ?>
                    <div class="col-md-8">

                        <?php
                        echo "<div class='form-group'>";
                        echo $this->formLabel($form->get('name')) . " ";
                        echo $this->formElement($form->get('name'));
                        echo $this->formElementErrors($form->get('name'));
                        echo "</div>";

                        echo "<div class='form-group'>";
                        echo $this->formLabel($form->get('description')) . " ";
                        echo $this->formElement($form->get('description'));
                        echo $this->formElementErrors($form->get('description'));
                        echo "</div>";

                        echo "<div class='form-group'>";
                        echo $this->formLabel($form->get('image')) . " ";
                        echo $this->formElement($form->get('image'));
                        echo $this->formElementErrors($form->get('image'));
                        echo "</div>";

                        echo $this->formElement($form->get('submit'));
                        ?>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
