<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Danh sách thể loại</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Danh sách
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $basePath = $this->basePath();
                        foreach ($this->categories as $category) :
                        ?>
                        <tr class="odd gradeX">
                            <td><?=$category->getId() ?></td>
                            <td><?=$category->getName() ?></td>
                            <td>  <img width='150' height='150' src="<?php echo $basePath.'/data/image/'. $category->getImage(); ?>" ></td>
                            <td class="center"><a href="<?php 
                                $this->url('admin/category',array('action'=>'edit','id'=>$category->getId() ) );
                            ?>"> Sửa </a> </td>
                            <td class="center"><a href="<?php 
                                $this->url('admin/category',array('action'=>'delete','id'=>$category->getId() ) );
                            ?>"> Xóa </a> </td>
                        </tr>
                        <?php endforeach;   ?>
                    </tbody>
                </table>
                <!-- /.table-responsive -->
                <div class="well">
                    <h4>DataTables Usage Information</h4>
                    <p>DataTables is a very flexible, advanced tables plugin for jQuery. In SB Admin, we are using a specialized version of DataTables built for Bootstrap 3. We have also customized the table headings to use Font Awesome icons in place of images. For complete documentation on DataTables, visit their website at <a target="_blank" href="https://datatables.net/">https://datatables.net/</a>.</p>
                    <a class="btn btn-default btn-lg btn-block" target="_blank" href="https://datatables.net/">View DataTables Documentation</a>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>