<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Flower Shop '. $this->translate('Web bán hoa -Zend Framework 2'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/admin1/vendor/bootstrap/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/admin1/vendor/metisMenu/metisMenu.min.css')
        ->prependStylesheet($this->basePath() . '/admin1/dist/css/sb-admin-2.css')
        ->prependStylesheet($this->basePath() . '/admin1/vendor/morrisjs/morris.css')
        ->prependStylesheet($this->basePath() . '/admin1/vendor/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/script.js')
        ->prependFile($this->basePath() . '/admin1/dist/js/sb-admin-2.js')
        ->prependFile($this->basePath() . '/admin1/data/morris-data.js')
        ->prependFile($this->basePath() . '/admin1/vendor/morrisjs/morris.min.js')
        ->prependFile($this->basePath() . '/admin1/vendor/raphael/raphael.min.js')

        ->prependFile($this->basePath() . '/admin1/vendor/metisMenu/metisMenu.min.js')
        ->prependFile($this->basePath() . '/admin1/vendor/bootstrap/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/admin1/vendor/jquery/jquery.min.js')

//        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
<!--     Scripts -->
<!--    --><?php //echo $this->headScript()
//        ->prependFile($this->basePath() . '/admin1/vendor/jquery/jquery.min.js')
//        ->prependFile($this->basePath() . '/admin1/vendor/bootstrap/js/bootstrap.min.js')
//        ->prependFile($this->basePath() . '/admin1/vendor/metisMenu/metisMenu.min.js')
//        ->prependFile($this->basePath() . '/admin1/vendor/raphael/raphael.min.js')
//        ->prependFile($this->basePath() . '/admin1/vendor/morrisjs/morris.min.js')
//        ->prependFile($this->basePath() . '/admin1/data/morris-data.js')
//        ->prependFile($this->basePath() . '/admin1/dist/js/sb-admin-2.js')
//
//        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
//    ; ?>

</head>


<body>
<div id="wrapper">
    <!-- Navigation -->

    <?php
        echo $this->Layout()->callTopMenu();
    ?>

    <div id="page-wrapper">

        <?php 
        echo $this->content; ?>
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery-->



<!-- <script src="../admin1/vendor/jquery/jquery.min.js"></script>
<script src="../admin1/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../admin1/vendor/metisMenu/metisMenu.min.js"></script>
<script src="../admin1/vendor/raphael/raphael.min.js"></script>
<script src="../admin1/vendor/morrisjs/morris.min.js"></script>
<script src="../admin1/data/morris-data.js"></script>
<script src="../admin1/dist/js/sb-admin-2.js"></script> -->
<?php echo $this->inlineScript() ?>
</body>


<!--<body>-->
<!--<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
<!--    <div class="container">-->
<!--        <div class="navbar-header">-->
<!--            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--                <span class="icon-bar"></span>-->
<!--                <span class="icon-bar"></span>-->
<!--                <span class="icon-bar"></span>-->
<!--            </button>-->
<!--            <a class="navbar-brand" href="--><?php //echo $this->url('home') ?><!--"><img src="--><?php //echo $this->basePath('img/zf2-logo.png') ?><!--" alt="Zend Framework 2"/>&nbsp;--><?php //echo $this->translate('Doctrine') ?><!--</a>-->
<!--        </div>-->
<!--        <div class="collapse navbar-collapse">-->
<!--            <ul class="nav navbar-nav">-->
<!--                <li class="active"><a href="--><?php //echo $this->url('home') ?><!--">--><?php //echo $this->translate('Home') ?><!--</a></li>-->
<!--            </ul>-->
<!--        </div><!--/.nav-collapse -->
<!--    </div>-->
<!--</nav>-->
<!--<div class="container">-->
<!--    --><?php //echo $this->content; ?>
<!--    <hr>-->
<!--    <footer>-->
<!--        <p>&copy; 2005 - --><?php //echo date('Y') ?><!-- by Zend Technologies Ltd. --><?php //echo $this->translate('All rights reserved.') ?><!--</p>-->
<!--    </footer>-->
<!--</div> <!-- /container -->
<?php //echo $this->inlineScript() ?>
<!--</body>-->


</html>
