<?php
//echo $this->headStyle()
//    ->appendStyle($this->basePath().'/vendor/datatables-plugins/dataTables.bootstrap.css')
//    ->appendStyle($this->basePath().'/vendor/datatables-responsive/dataTables.responsive.css');
//
$this->inlineScript()->captureStart();
echo <<<JS
    $("div.alert-success").fadeOut(3000);
JS;
$this->inlineScript()->captureEnd();
?>


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Danh sách sản phẩm</h1>
        <?php
        if (count($flash)) {
            $message = $flash;
            echo "<div class='alert-success alert'> ";
            foreach ($message as $mess) {
                echo $mess;
            }
            echo "</div>";
        }
        ?>
    </div>


</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Danh sách sản phẩm
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Unit</th>
                        <th>Category</th>
                        <th>Quantity</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $basePath = $this->basePath();
                    foreach ($products as $product) :
                        $nameUrl = $this->Unicode()->make($product->getName());
                        ?>
                        <tr class="odd gradeX">
                            <td><?= $product->getId() ?></td>
                            <td><?= $product->getName() ?></td>
                            <td><?= $product->getUnitPrice() ?></td>
                            <td><?= $product->getUnit()->getName() ?></td>
                            <td><?= $product->getCategory()->getName() ?></td>
                            <td><?= $product->getQuantity() ?></td>
                            <td class="center"><a href="<?= $this->url('admin/product', array('action'=>'edit','id'=> $product->getId(),'name'=>$nameUrl)); ?>">Sửa</a></td>
                            <td class="center"><a href="<?= $this->url('admin/product', array('action'=>'delete','id'=> $product->getId())); ?>" onClick='return confirm_delete_product();'>Xoá</a></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <div class="panel-footer">
            <?php
            echo $this->paginationControl(
                $products,
                'sliding',
                array('partial/pagination.phtml','admin'),
                array(
                    'route' => 'admin/product',
                    'params' => array('action' => 'index')
                )
            );
            ?>
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/admin1/vendor/datatables-responsive/dataTables.responsive.js')
    ->prependFile($this->basePath() . '/admin1/vendor/datatables-plugins/dataTables.bootstrap.min.js')
    ->prependFile($this->basePath() . '/admin1/vendor/datatables/js/jquery.dataTables.min.js'); ?>

